import type { Farm } from "./types";

const fictionalSource = (id: string) => ({
  id: `fictional-${id}`,
  sourceName: "Discovery fictional seed data",
  sourceUrl: "https://example.invalid/discovery-seed-data",
  externalId: `seed-${id}`,
  importedAt: "2026-01-01T00:00:00.000Z",
  lastCheckedAt: "2026-01-01T00:00:00.000Z",
  usageNotes:
    "Fictional demonstration record created for local development; not copied from Eatwild or any farm directory.",
  metadata: { license: "Project-owned fictional sample data" },
});

export const seedFarms: Farm[] = [
  {
    id: "farm-green-valley",
    slug: "green-valley-pastures",
    name: "Green Valley Pastures",
    description:
      "A fictional family farm offering pasture-raised meats, eggs, and seasonal pickup shares for demo searches.",
    address: {
      street: "100 Clover Demo Lane",
      city: "Lancaster",
      state: "PA",
      postalCode: "17602",
      country: "US",
    },
    coordinates: { latitude: 40.0379, longitude: -76.3055 },
    phone: "(555) 010-1701",
    email: "hello@greenvalley.example",
    website: "https://greenvalley.example",
    socialLinks: [{ label: "Instagram", url: "https://social.example/greenvalley" }],
    visitInfo: "Pre-order pickup at the farm lane. Please do not enter barns without an appointment.",
    hours: "Friday 2 PM–6 PM; Saturday 9 AM–1 PM",
    seasonalAvailability: "Eggs year-round; beef and chicken shares released seasonally.",
    products: [
      {
        id: "gv-beef",
        category: "meat",
        name: "Beef",
        details: "Quarter and half shares listed when available.",
        availability: "seasonal",
        season: "Spring and fall",
      },
      {
        id: "gv-eggs",
        category: "eggs",
        name: "Chicken eggs",
        details: "Weekly pickup cartons.",
        availability: "year-round",
      },
    ],
    salesMethods: ["pickup", "csa", "farmers-market"],
    practiceClaims: [
      {
        label: "Pasture-raised claim",
        note: "Owner-submitted practice claim in seed data; not independently certified by Discovery.",
      },
    ],
    claimStatus: "owner-claimed",
    publicationStatus: "published",
    verificationStatus: "admin-verified",
    lastVerifiedAt: "2026-01-15T00:00:00.000Z",
    sourceRecords: [fictionalSource("green-valley")],
    isFictionalSeed: true,
  },
  {
    id: "farm-sunrise-orchard",
    slug: "sunrise-orchard-garden",
    name: "Sunrise Orchard & Garden",
    description:
      "Fictional orchard and vegetable grower with a roadside stand, honey, flowers, and u-pick weekends.",
    address: {
      street: "42 Orchard Demo Road",
      city: "Charlottesville",
      state: "VA",
      postalCode: "22902",
      country: "US",
    },
    coordinates: { latitude: 38.0293, longitude: -78.4767 },
    phone: "(555) 010-2290",
    website: "https://sunriseorchard.example",
    socialLinks: [],
    visitInfo: "Roadside stand with accessible parking near the packing shed.",
    hours: "Wednesday–Sunday 10 AM–5 PM, May through November",
    seasonalAvailability: "Vegetables in summer; apples and cut flowers in late summer and fall.",
    products: [
      {
        id: "so-veg",
        category: "produce",
        name: "Seasonal vegetables",
        details: "Greens, tomatoes, squash, and storage crops.",
        availability: "seasonal",
        season: "May–November",
      },
      {
        id: "so-honey",
        category: "honey",
        name: "Wildflower honey",
        details: "Small-batch jars at the stand.",
        availability: "seasonal",
        season: "Summer and fall",
      },
      {
        id: "so-flowers",
        category: "flowers",
        name: "Cut flowers",
        details: "Mixed bouquets while blooming.",
        availability: "seasonal",
      },
    ],
    salesMethods: ["farm-stand", "pickup", "farmers-market"],
    practiceClaims: [
      {
        label: "Integrated pest management claim",
        note: "Practice claim is represented as submitted, not as a Discovery endorsement.",
      },
    ],
    claimStatus: "unclaimed",
    publicationStatus: "published",
    verificationStatus: "community-submitted",
    lastVerifiedAt: "2026-02-01T00:00:00.000Z",
    sourceRecords: [fictionalSource("sunrise-orchard")],
    isFictionalSeed: true,
  },
  {
    id: "farm-riverbend-creamery",
    slug: "riverbend-creamery",
    name: "Riverbend Creamery",
    description:
      "Fictional dairy producing cheese, yogurt, and bottled milk with local delivery routes.",
    address: {
      street: "8 Milkhouse Demo Pike",
      city: "Madison",
      state: "WI",
      postalCode: "53703",
      country: "US",
    },
    coordinates: { latitude: 43.0748, longitude: -89.3838 },
    phone: "(555) 010-5309",
    email: "orders@riverbendcreamery.example",
    website: "https://riverbendcreamery.example",
    socialLinks: [{ label: "Facebook", url: "https://social.example/riverbendcreamery" }],
    visitInfo: "Creamery store entrance is marked from the south parking lot.",
    hours: "Tuesday–Friday 11 AM–6 PM; Saturday 9 AM–2 PM",
    seasonalAvailability: "Milk and yogurt year-round; specialty cheeses rotate monthly.",
    products: [
      {
        id: "rc-milk",
        category: "dairy",
        name: "Milk and yogurt",
        details: "Whole milk, drinkable yogurt, and cultured products.",
        availability: "year-round",
      },
      {
        id: "rc-cheese",
        category: "dairy",
        name: "Farmstead cheese",
        details: "Cheddar-style blocks and seasonal soft cheeses.",
        availability: "year-round",
      },
    ],
    salesMethods: ["farm-stand", "delivery", "shipping"],
    practiceClaims: [
      {
        label: "Animal welfare claim",
        note: "Listed as a claim from the farm profile; certification documentation is not attached in seed data.",
      },
    ],
    claimStatus: "owner-claimed",
    publicationStatus: "published",
    verificationStatus: "owner-claimed",
    lastVerifiedAt: "2026-01-20T00:00:00.000Z",
    sourceRecords: [fictionalSource("riverbend-creamery")],
    isFictionalSeed: true,
  },
  {
    id: "farm-prairie-roots",
    slug: "prairie-roots-farm",
    name: "Prairie Roots Farm",
    description:
      "Fictional diversified farm supplying CSA boxes, poultry, baked goods, and winter pantry items.",
    address: {
      street: "315 Prairie Demo Trail",
      city: "Ames",
      state: "IA",
      postalCode: "50010",
      country: "US",
    },
    coordinates: { latitude: 42.0308, longitude: -93.6319 },
    phone: "(555) 010-5010",
    website: "https://prairieroots.example",
    socialLinks: [],
    visitInfo: "CSA pickup shed is open during posted windows only.",
    hours: "CSA pickup Tuesday 4 PM–7 PM; market Saturdays",
    seasonalAvailability: "CSA boxes June through October; baked goods and pantry staples year-round by order.",
    products: [
      {
        id: "pr-produce",
        category: "produce",
        name: "CSA vegetables",
        details: "Weekly boxes with greens, herbs, roots, and summer fruiting crops.",
        availability: "seasonal",
        season: "June–October",
      },
      {
        id: "pr-poultry",
        category: "meat",
        name: "Chicken",
        details: "Frozen whole birds after processing dates.",
        availability: "seasonal",
      },
      {
        id: "pr-bread",
        category: "prepared-foods",
        name: "Sourdough bread",
        details: "Order-ahead loaves for CSA members.",
        availability: "year-round",
      },
    ],
    salesMethods: ["csa", "pickup", "farmers-market"],
    practiceClaims: [
      {
        label: "No-spray vegetable claim",
        note: "Practice claim appears as submitted and should be verified before promotional use.",
      },
    ],
    claimStatus: "unclaimed",
    publicationStatus: "published",
    verificationStatus: "imported",
    lastVerifiedAt: "2025-10-01T00:00:00.000Z",
    sourceRecords: [fictionalSource("prairie-roots")],
    isFictionalSeed: true,
  },
];
